export const siteConfig = {
  name: "Yashwanth Reddy S",
  role: "Full Stack Developer, AI Builder, and Creative Technologist",
  location: "Karnataka, India",
  email: "yashwanthreddy05official@gmail.com",
  description:
    "A futuristic developer portfolio crafted with immersive motion, glassmorphism, and high-performance interactive experiences.",
  resumeUrl: "#contact",
  socialLinks: [
    { label: "GitHub", href: "https://github.com/yashwanth145", value: "@yashwanth145" },
    {
      label: "LinkedIn",
      href: "https://www.linkedin.com/in/yashwanth-reddy-623396305/",
      value: "/in/yashwanth-reddy",
    },
    {
      label: "Email",
      href: "mailto:yashwanthreddy05official@gmail.com",
      value: "Let's talk",
    },
  ],
  navItems: [
    { label: "Home", href: "/" },
    { label: "Projects", href: "/projects" },
    { label: "About", href: "/about" },
    { label: "Skills", href: "/skills" },
    { label: "Experience", href: "/experience" },
    { label: "Certifications", href: "/certifications" },
    { label: "Contact", href: "/contact" },
  ],
};

export const stats = [
  { value: "35+", label: "Projects shipped" },
  { value: "15+", label: "Technology domains" },
  { value: "99%", label: "Performance-driven mindset" },
];

export const aboutCards = [
  {
    title: "Product-focused builder",
    description:
      "I build polished web experiences that blend engineering, motion design, and storytelling into memorable products.",
  },
  {
    title: "AI + automation mindset",
    description:
      "From modern frontends to intelligent workflows, I enjoy creating systems that feel powerful, fast, and intuitive.",
  },
  {
    title: "Scalable craftsmanship",
    description:
      "My approach prioritizes clean architecture, reusable components, and performance from the first commit.",
  },
];

export const journey = [
  {
    year: "2023",
    title: "Started deeper frontend exploration",
    description: "Focused on React, UI engineering, and building richer user-first interfaces.",
  },
  {
    year: "2024",
    title: "Expanded into full-stack projects",
    description: "Built applications with authentication, APIs, databases, and interactive product flows.",
  },
  {
    year: "2025",
    title: "Blended AI with product design",
    description: "Started combining AI workflows, automation, and premium interface design into modern apps.",
  },
  {
    year: "2026",
    title: "Crafting immersive portfolio experiences",
    description: "Pushing deeper into motion, 3D, and high-performance personal branding on the web.",
  },
];

export const learningAreas = [
  {
    title: "Programming Languages",
    items: [
      "Java",
      "Python",
      "C",
      "Embedded C",
      "ARM Assembly",
      "JavaScript",
      "TypeScript",
      "HTML5",
      "CSS3",
      "SQL",
    ],
  },
  {
    title: "Data Structures & Algorithms",
    items: [
      "Arrays",
      "Strings",
      "Linked Lists",
      "Stacks",
      "Queues",
      "Trees",
      "Graphs",
      "Recursion",
      "Searching & Sorting",
      "LeetCode Problem Solving",
    ],
  },
  {
    title: "Frontend Frameworks",
    items: [
      "React.js",
      "Next.js",
      "React Native",
      "Vite",
      "Tailwind CSS",
      "Bootstrap",
      "shadcn/ui",
      "Framer Motion",
      "GSAP",
      "Three.js",
      "React Three Fiber",
      "Responsive UI Design",
    ],
  },
  {
    title: "Backend Frameworks",
    items: [
      "Node.js",
      "Express.js",
      "FastAPI",
      "Flask",
      "Django",
      "Spring Boot",
      "REST API Development",
      "GraphQL Basics",
      "Authentication & Authorization",
      "JWT",
      "OAuth 2.0",
      "Socket.io",
      "WebSockets",
      "WebRTC",
      "Backend Architecture",
      "Microservices Basics",
    ],
  },
  {
    title: "Databases & Data Stores",
    items: [
      "MySQL",
      "PostgreSQL",
      "MongoDB",
      "Redis",
      "Firestore",
      "Supabase",
      "SQL Query Optimization",
      "Database Design",
      "Database Integration",
      "ORM / ODM Patterns",
    ],
  },
  {
    title: "Mobile Development",
    items: [
      "React Native",
      "Expo",
      "Android Development Fundamentals",
      "Mobile UI Patterns",
      "Cross-Platform Apps",
    ],
  },
  {
    title: "Artificial Intelligence & Machine Learning",
    items: [
      "Machine Learning",
      "Deep Learning",
      "TensorFlow",
      "PyTorch",
      "scikit-learn",
      "Pandas",
      "NumPy",
      "Jupyter Notebook",
      "Transformers",
      "Hugging Face",
      "LangChain",
      "OpenAI API",
      "Large Language Models (LLMs)",
      "Generative AI",
      "Natural Language Processing",
      "Recommendation Systems",
      "AI Model Integration",
    ],
  },
  {
    title: "Computer Vision",
    items: [
      "OpenCV",
      "YOLO",
      "MediaPipe",
      "Gesture Recognition",
      "Human Detection",
      "Face Analysis",
      "Eye Tracking Research",
      "Image Preprocessing",
    ],
  },
  {
    title: "Cybersecurity Tools",
    items: [
      "Kali Linux",
      "Nmap",
      "Nikto",
      "Wireshark",
      "Burp Suite",
      "Metasploit Basics",
      "SET Toolkit",
      "Network Scanning & Enumeration",
      "Vulnerability Assessment",
      "Reconnaissance Techniques",
      "Web Application Security",
      "Network Security",
      "Cisco Packet Tracer",
      "Ethical Hacking Fundamentals",
      "Linux Security",
    ],
  },
  {
    title: "Networking",
    items: [
      "TCP/IP",
      "OSI Model",
      "Routing & Switching",
      "Subnetting",
      "VLANs",
      "DNS",
      "DHCP",
      "HTTP/HTTPS",
      "WebSockets",
      "Network Troubleshooting",
    ],
  },
  {
    title: "Cloud Platforms",
    items: [
      "Firebase",
      "Supabase",
      "Vercel",
      "Netlify",
      "AWS Fundamentals",
      "AWS EC2",
      "AWS S3",
      "AWS Lambda",
      "Google Cloud Platform (GCP)",
      "Microsoft Azure",
      "Cloudflare",
      "Serverless Deployment",
      "Cloud Storage",
      "Managed Databases",
    ],
  },
  {
    title: "DevOps & Infrastructure",
    items: [
      "Docker",
      "Docker Compose",
      "Kubernetes (K8s)",
      "Container Orchestration",
      "Terraform",
      "Ansible",
      "Infrastructure as Code (IaC)",
      "GitHub Actions",
      "GitLab CI/CD",
      "Jenkins",
      "CI/CD Pipelines",
      "Continuous Integration",
      "Continuous Deployment",
      "Nginx",
      "Reverse Proxy Setup",
      "Linux Server Administration",
      "Bash Scripting",
      "Shell Automation",
      "Environment Variables & Secrets",
      "Monitoring & Logging",
      "Prometheus",
      "Grafana",
      "Deployment Automation",
      "Blue-Green Deployment",
      "Rolling Updates",
      "DevSecOps Basics",
      "Helm Charts",
    ],
  },
  {
    title: "Embedded Systems & IoT",
    items: [
      "LPC214x ARM Controllers",
      "Arduino",
      "Raspberry Pi",
      "LCD Interfacing",
      "Keypad Interfacing",
      "DAC Interfacing",
      "Stepper Motors",
      "Seven Segment Displays",
      "Microcontroller Programming",
      "IoT Protocols",
    ],
  },
  {
    title: "Software Engineering",
    items: [
      "Full-Stack Development",
      "API Integration",
      "SaaS Product Design",
      "System Design Fundamentals",
      "Agile / Scrum",
      "Git & GitHub",
      "Code Reviews",
      "Debugging & Testing",
      "Unit Testing",
      "Technical Documentation",
    ],
  },
  {
    title: "Development Software & Tools",
    items: [
      "VS Code",
      "Cursor",
      "GitHub",
      "GitLab",
      "Postman",
      "Insomnia",
      "npm / pnpm",
      "Chrome DevTools",
      "Figma",
      "Jira",
      "Notion",
      "MongoDB Compass",
      "MySQL Workbench",
      "Docker Desktop",
      "Windows Terminal",
      "PowerShell",
    ],
  },
  {
    title: "Emerging Technologies",
    items: [
      "Blockchain Fundamentals",
      "Generative AI Applications",
      "AI-Powered Web Applications",
      "RAG Pipelines",
      "Edge AI",
      "Web3 Basics",
    ],
  },
];

export const certifications = [
  {
    name: "NIT Karnataka Competition Participation",
    issuer: "NIT Karnataka",
    category: "Competition",
    href: "/cert/nitk-competition.pdf",
  },
  {
    name: "CCNA: Enterprise Networking, Security, and Automation",
    issuer: "Cisco Networking Academy",
    category: "Networking",
    href: "/cert/ccna-enterprise-networking-security-automation.pdf",
  },
  {
    name: "CCNA: Switching, Routing, and Wireless Essentials",
    issuer: "Cisco Networking Academy",
    category: "Networking",
    href: "/cert/ccna-switching-routing-wireless-essentials.pdf",
  },
  {
    name: "CCNA: Introduction to Networks",
    issuer: "Cisco Networking Academy",
    category: "Networking",
    href: "/cert/ccna-introduction-to-networks.pdf",
  },
  {
    name: "Networking Basics",
    issuer: "Cisco Networking Academy",
    category: "Networking",
    href: "/cert/networking-basics.pdf",
  },
  {
    name: "Ethical Hacker",
    issuer: "Cisco Networking Academy",
    category: "Cybersecurity",
    href: "/cert/ethical-hacker.pdf",
  },
  {
    name: "Introduction to Modern AI",
    issuer: "Cisco Networking Academy",
    category: "AI & Data",
    href: "/cert/introduction-to-modern-ai.pdf",
  },
  {
    name: "Introduction to Data Science",
    issuer: "Cisco Networking Academy",
    category: "AI & Data",
    href: "/cert/introduction-to-data-science.pdf",
  },
  {
    name: "Python Essentials 1",
    issuer: "Cisco Networking Academy",
    category: "Programming",
    href: "/cert/python-essentials-1.pdf",
  },
  {
    name: "Python Essentials 2",
    issuer: "Cisco Networking Academy",
    category: "Programming",
    href: "/cert/python-essentials-2.pdf",
  },
];

export const experiences = [
  {
    role: "Full Stack Developer Intern",
    company: "ELVA",
    location: "Remote",
    duration: "2024",
    summary:
      "Engineered scalable web and mobile application features using React.js, Node.js, Express.js, MongoDB, and REST APIs. Improved backend performance by 30% through query optimization and efficient API design. Delivered production-ready features using Agile methodologies, Git version control, and CI/CD workflows.",
    highlights: [
      "Developed scalable full-stack web and mobile application features using React.js, Node.js, Express.js, MongoDB, and REST APIs.",
      "Integrated frontend and backend modules to deliver seamless user experiences across web and app platforms.",
      "Optimized database queries and API design, improving backend performance by 30%.",
      "Built and maintained secure RESTful APIs for efficient data exchange and application functionality.",
      "Collaborated in Agile development environments, using Git and CI/CD workflows to deliver production-ready features.",
      "Contributed to cloud-based application deployment and maintenance, gaining experience with scalable architectures and modern development practices.",
      "Worked with cross-functional teams to analyze requirements, implement features, test functionality, and resolve bugs.",
    ],
    skills: [
      "Full-Stack Development",
      "REST API Development",
      "React.js",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Database Optimization",
      "Git & GitHub",
      "CI/CD",
      "Agile Development",
      "Backend Performance Tuning",
      "Cloud Application Deployment",
      "Team Collaboration & Code Reviews",
    ],
  },
];
